### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by sakherg** [lmb-freiburg/netdef-docker#13]
Hello,
I tried to make the makefile, but met the following problom:

...
docker build                    \
       -f Dockerfile            \
       -t lmb-freiburg-netdef   \
       --build-arg uid=$UID    \
       --build-arg gid=$GROUPS \
       .
Sending build context to Docker daemon  57.34kB
Step 1/17 : FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
 ---> a387f44414ed
Step 2/17 : VOLUME "/input"
 ---> Using cache
 ---> 137fbdea5b25
Step 3/17 : VOLUME "/output"
 ---> Using cache
 ---> 6ca6bba700f7
Step 4/17 : RUN apt update                             &&     apt install -y --no-install-recommends        python3                                       python3-distutils                             cmake                                         git                                           curl                                          wget                                          libeigen3-dev                                 sudo
 ---> Using cache
 ---> 98e17b1df448
Step 5/17 : ARG uid
 ---> Using cache
 ---> e49ed872d35b
Step 6/17 : ARG gid
 ---> Using cache
 ---> 2a40b7dbe14d
Step 7/17 : ENV uid=${uid}
 ---> Using cache
 ---> 5239c285b4d1
Step 8/17 : ENV gid=${gid}
 ---> Using cache
 ---> a489c0b827ef
Step 9/17 : ENV USER=netdef
 ---> Using cache
 ---> 59194799fb6a
Step 10/17 : RUN groupadd -g $gid $USER                                              &&     mkdir -p /home/$USER                                                &&     echo "${USER}:x:${uid}:${gid}:${USER},,,:/home/${USER}:/bin/bash"               >> /etc/passwd                                                 &&     echo "${USER}:x:${uid}:"                                                        >> /etc/group                                                  &&     echo "${USER} ALL=(ALL) NOPASSWD: ALL"                                          > /etc/sudoers.d/${USER}                                       &&     chmod 0440 /etc/sudoers.d/${USER}                                   &&     chown ${uid}:${gid} -R /home/${USER}
 ---> Running in 48177b3a526e
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g $gid $USER                                              &&     mkdir -p /home/$USER                                                &&     echo "${USER}:x:${uid}:${gid}:${USER},,,:/home/${USER}:/bin/bash"               >> /etc/passwd                                                 &&     echo "${USER}:x:${uid}:"                                                        >> /etc/group                                                  &&     echo "${USER} ALL=(ALL) NOPASSWD: ALL"                                          > /etc/sudoers.d/${USER}                                       &&     chmod 0440 /etc/sudoers.d/${USER}                                   &&     chown ${uid}:${gid} -R /home/${USER}' returned a non-zero code: 4
Makefile:12: recipe for target 'lmb-freiburg-netdef' failed
make: *** [lmb-freiburg-netdef] Error 4

Could anyone help with this error? 
THANKS A LOT!

**Comment by nikolausmayer** [comment]
The error `groupadd: GID '0' already exists` sounds to me like you are building as a superuser. Did you perhaps run `sudo make` instead of `make`?

**Comment by sakherg** [comment]
Thank you for your response. The above error is from running "sudo make".
When I run "make" alone this error is appear:

docker build                    \
       -f Dockerfile            \
       -t lmb-freiburg-netdef   \
       --build-arg uid=$UID    \
       --build-arg gid=$GROUPS \
       .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/build?buildargs=%7B%22gid%22%3A%221005%22%2C%22uid%22%3A%221005%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=0t8kfs690gb5otil1rb4mcwvt&shmsize=0&t=lmb-freiburg-netdef&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
Makefile:12: recipe for target 'lmb-freiburg-netdef' failed
make: *** [lmb-freiburg-netdef] Error 1

**Comment by sakherg** [comment]
I don't know why, but I restart my computer and run "make" command again and it works fine. 
Thank you!
