### ISSUE TITLE
Question about .float3 file 

### ISSUE THREAD

**Issue by Tsugikuni-Yoriichi** [lmb-freiburg/netdef-docker#5]
I have tried your network about optical flow computation.
I am not sure about its performance compared to flownet2. 

I also tried your Convolutional Networks for Disparity.
After I get the .float3 file. I don't know how to import it to numpy.
I tried the possible way:

f = open("xxxx.float3")
f.read(6)  # float3\n
dispData = np.fromfile(f, np.float32, w*h)  # reshape after

Is the data I imported correct?

**Comment by nikolausmayer** [comment]
IO methods for the .float3 format are available in https://github.com/lmb-freiburg/netdef_slim/blob/master/utils/io.py#L29

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
