### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by GallonDeng** [lmb-freiburg/netdef-docker#6]
Hi, thanks for your great works. I just follow the instructions. And successfully build the docker image. It occurs error:
stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=14997 /var/lib/docker/overlay2/ecce4a589a179632f8387436a404d6c010786cad0df7e304ae90b1a605a22197/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: driver < 385\\\\n\\\"\"": unknown

My host computer has installed cudaV9.0.176, NVIDIA-SMI 390.77, GPU Tesla P100

**Comment by nikolausmayer** [comment]
Hi,
I have never tested a Tesla card. It seems that Nvidia's Docker runtime poses special restrictions here: `cuda>=10.0 brand=tesla,driver>=384,driver<385` sounds like you need a 384 driver version.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
