### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by decai-chen** [lmb-freiburg/netdef-docker#8]
Hello,
I tried to make the makefile, but met the following problom:

...
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-19.1.1 setuptools-41.0.1 wheel-0.33.4
--2019-07-17 15:20:22--  https://lmb.informatik.uni-freiburg.de/resources/binaries/tensorflow-binaries/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl
Resolving lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)... 132.230.167.23
Connecting to lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)|132.230.167.23|:443... connected.
ERROR: cannot verify lmb.informatik.uni-freiburg.de's certificate, issued by 'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE':
  Unable to locally verify the issuer's authority.
To connect to lmb.informatik.uni-freiburg.de insecurely, use `--no-check-certificate'.
The command '/bin/sh -c sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py   &&     sudo python3 get-pip.py                                        &&     wget https://lmb.informatik.uni-freiburg.de/resources/binaries/tensorflow-binaries/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl &&     sudo -H pip3 install -r requirements.txt                       &&     sudo -H pip3 install ${HOME}/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl &&     sudo -H pip3 install scikit-learn pillow scipy' returned a non-zero code: 5
Makefile:12: recipe for target 'lmb-freiburg-netdef' failed
make: *** [lmb-freiburg-netdef] Error 5

Could anyone help with this problem? THANKS A LOT!

**Comment by nikolausmayer** [comment]
Hi,

our webserver (from which the network snapshots are pulled) is currently not correctly configured, so `wget` complains about an "unsafe connection".
I have disabled the certificate checks in https://github.com/lmb-freiburg/netdef_models/commit/7d3311579cf712b31d05ec29f3dc63df067aa07b until we can fix this serverside; you should now be able to build.

EDIT: You also need to pull to get https://github.com/lmb-freiburg/netdef-docker/commit/cd422f582297d552169a1d5eb083c3a1248555f2

**Comment by decai-chen** [comment]
Hi Nikolaus,

Thank you for solution!
There is another place you omitted, which was where my error came:

 the 47th line of Dockerfile:     
wget https://lmb.informatik.uni-freiburg.de/resources/binaries/tensorflow-binaries/tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl && \
I added --no-check-certificate and now it works.

**Comment by nikolausmayer** [comment]
Woops.. I should have read your error message properly. Thanks!

**Comment by saifrais** [comment]
I am facing the same problem. Any help here?
Cloning into 'flownet2'...
--2019-07-28 07:26:03--  https://lmb.informatik.uni-freiburg.de/resources/binaries/flownet2/flownet2-models.tar.gz
Resolving lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)... 132.230.167.23
Connecting to lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)|132.230.167.23|:443... connected.
ERROR: cannot verify lmb.informatik.uni-freiburg.de's certificate, issued by 'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE':
  Unable to locally verify the issuer's authority.
To connect to lmb.informatik.uni-freiburg.de insecurely, use `--no-check-certificate'.
tar (child): flownet2-models.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
--2019-07-28 07:26:03--  https://lmb.informatik.uni-freiburg.de/resources/binaries/flownet2/flownet2-models-kitti.tar.gz
Resolving lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)... 132.230.167.23
Connecting to lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)|132.230.167.23|:443... connected.
ERROR: cannot verify lmb.informatik.uni-freiburg.de's certificate, issued by 'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE':
  Unable to locally verify the issuer's authority.
To connect to lmb.informatik.uni-freiburg.de insecurely, use `--no-check-certificate'.
tar (child): flownet2-models-kitti.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
--2019-07-28 07:26:03--  https://lmb.informatik.uni-freiburg.de/resources/binaries/flownet2/flownet2-models-sintel.tar.gz
Resolving lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)... 132.230.167.23
Connecting to lmb.informatik.uni-freiburg.de (lmb.informatik.uni-freiburg.de)|132.230.167.23|:443... connected.
ERROR: cannot verify lmb.informatik.uni-freiburg.de's certificate, issued by 'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE':
  Unable to locally verify the issuer's authority.
To connect to lmb.informatik.uni-freiburg.de insecurely, use `--no-check-certificate'.
tar (child): flownet2-models-sintel.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         module-init-tools         build-essential         ca-certificates         wget         git         libatlas-base-dev         libboost-all-dev         libgflags-dev         libgoogle-glog-dev         libhdf5-serial-dev         libleveldb-dev         liblmdb-dev         libopencv-dev         libprotobuf-dev         libsnappy-dev         protobuf-compiler         python-dev         python-numpy         python-scipy         python-protobuf         python-pillow         python-skimage &&     git clone https://github.com/lmb-freiburg/flownet2 &&     cp ./FN2_Makefile.config ./flownet2/Makefile.config &&     cp ./FN2_run-flownet-docker.py ./flownet2/scripts/run-flownet-docker.py &&     cd flownet2 &&     rm -rf .git &&     cd models &&     bash download-models.sh &&     rm flownet2-models.tar.gz &&     cd .. &&     make -j`nproc` &&     make -j`nproc` pycaffe &&     apt-get remove -y         module-init-tools         build-essential         ca-certificates         git         wget &&     apt-get autoremove -y &&     apt-get autoclean -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
Makefile:7: recipe for target 'flownet2' failed
make: *** [flownet2] Error 2

**Comment by nikolausmayer** [comment]
@saifrais Please post issues in the repository to which they belong: https://github.com/lmb-freiburg/flownet2-docker resp. https://github.com/lmb-freiburg/flownet2
Fixed in https://github.com/lmb-freiburg/flownet2/commit/b92e198b56b0e52e1ba0a5a98dc0e39fa5ae70cc
