### ISSUE TITLE
running over video?

### ISSUE THREAD

**Issue by oddfox19** [lmb-freiburg/netdef-docker#9]
What's the best way to run netdef-docker over the frames of a video? Currently I am running run-network.sh in a loop, but is there a smarter way to do this without having to reset between each frame? Thanks.

**Comment by nikolausmayer** [comment]
Hi, the "netdef_slim" framework used here does not support this natively, but you could hack the `eval` method (https://github.com/lmb-freiburg/netdef_slim/blob/master/tensorflow/controller/net_actions.py#L38, called via https://github.com/lmb-freiburg/netdef_slim/blob/master/tensorflow/controller/base_controller.py#L89) to reuse its network instance for multiple inputs.

**Comment by oddfox19** [comment]
I was able to modify the code so that it accepts a file with multiple image pairs in a list and iterated through that calling session.run() on each pair of images. Thanks for leading me in the right direction!
